config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "pages#home"
  get "dashboard", to: "dashboard#show"
  resources :plants do
    resources :bookings, only: %i[new create show index]
  end
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :plant
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :end_date_is_after_start_date

  # private

  # def end_date_is_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   if end_date <= start_date
  #     errors.add(:end_date, "cannot be before the start date")
  #   end
  # end

  validates :start_date, :end_date, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, :plant_type, :age, :city, :price, presence: true
  validates :age, numericality: { only_integer: true }

  has_one_attached :photo

  # validates :name, :plant_type, :age, :city, :price, presence: true
  # validates :age, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar_url])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar_url])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: %i[destroy show update edit]
  before_action :find_plant, only: %i[new create index show update edit]

  def new
    @booking = Booking.new
  end

  def index; end

  def show; end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.plant = @plant
    @booking.save!
    # redirect_to plant_booking_path(@plant, @booking)
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def find_plant
    @plant = Plant.find(params[:plant_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @bookings = Booking.where(user: current_user)
    @plants = Plant.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def totry
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :find_plant, only: %i[show edit destroy update]

  def index
    if params[:query].present?
        @plants = Plant.where('city ILIKE ?', "%#{params[:query]}%")
    else
      @plants = Plant.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    @plant.save
    redirect_to plant_path(@plant)
  end

  def edit
  end

  def update
    @plant.update(plant_params)
    redirect_to plant_path(@plant)
  end

  def destroy
    @plant.destroy
    redirect_to plant_path, status: :see_other
  end

  private

  def find_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:name, :plant_type, :city, :age, :price, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_popup.html.erb
<div class="modal fade" id="booking_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content booking-confirmation__box">
          <%# <img class="booking-confirmation__gif-confirm" src="gif-confirmation-01.gif"> %>
          <%= image_tag "gif-confirmation-01.gif", class: "booking-confirmation__gif-confirm" %>
          <div class="booking-confirmation__title">Congratulations!<br>You just booked this plant!</div>
          <%= image_tag "gif-plant-01.gif", class: "booking-confirmation__gif-plant" %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>YOU ARE IN THE INDEX OF THE BOOKINGS</h1>

app/views/bookings/show.html.erb
<div class="alert alert-success" role="alert">
  Booked <%= @plant.name%>  from <%= @booking.start_date%> untill <%= @booking.end_date%> succesfully!!!
</div>
<br>
<%= link_to "Go back to the homepage!", root_path %>

app/views/dashboard/show.html.erb
<div class="dashboard-body">
  <div class="container p-2">
    <h1 class="dash-header">Dashboard</h1>
  </div>

  <div class="container d-flex p-2">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="#">Plants you've booked</a>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link active" href="#">Previous bookings</a>
      </li> %>
    </ul>
  </div>

  <div class="booking-area">
    <% @bookings.each do |booking| %>
        <div class="single-booking-box">
          <div class="booking-img-area">
            <%= cl_image_tag(booking.plant.photo.key, style: 'width: 100%; object-fit: cover;', height: 180, crop: :fill) %>
          </div>
          <div class="booking-img-text">
            <span class="booking-name-text"><span><strong><%= booking.plant.name %></strong></span><br>
            <span class="booking-detail-text">Start: <%= booking.start_date.day %>.<%= booking.start_date.month %>.<%= booking.start_date.year %></span><br>
            <span class="booking-detail-text">End: <%= booking.end_date.day %>.<%= booking.end_date.month %>.<%= booking.end_date.year %></span><br>
            <span class="booking-detail-text">Price: €<%= booking.plant.price %>/day</span><br>
            <div class="dash-buttons btns-wrp">
              <%= link_to 'See plant', plant_path(booking.plant), class: 'btn btn-primary btn-sm btn-custom btn-plants' %>
              <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this plant from your bookings?"}, class: 'btn btn-outline-primary btn-sm btn-custom btn-delete' %>
            </div>
          </div>
        </div>
    <%end%>
  </div>

  <div class="container d-flex p-2">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="#">Plants you're currently listing</a>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link active" href="#">Previous bookings</a>
      </li> %>
    </ul>
  </div>

  <div class="booking-area">
    <% @plants.each do |plant| %>
        <div class="single-booking-box">
          <div class="booking-img-area">
            <%= cl_image_tag(plant.photo.key, style: 'width: 100%; object-fit: cover;', height: 180, crop: :fill) %>
          </div>
          <div class="booking-img-text">
            <span class="booking-name-text"><strong><%= plant.name %></strong></span><br>
            <span class="booking-detail-text">Type: <%= plant.plant_type %></span><br>
            <span class="booking-detail-text">Age: <%= plant.age %> years old</span><br>
            <span class="booking-detail-text">Price: €<%= plant.price %>/day</span><br>
            <div class="dash-buttons btns-wrp">
              <%= link_to 'See plant', plant_path(plant), class: 'btn btn-primary btn-sm btn-custom btn-plants' %>
              <%= link_to "Delete", plant_path(plant), class:"btn btn-outline-primary btn-sm btn-custom btn-delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this plant from your bookings?"} %>
            </div>
          </div>
        </div>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPlantApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet"> %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  </head>

  <body>

  <%= render "shared/navbar" %>

   <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home backgroundimg" style="background-image: linear-gradient(
                                                            180deg,
                                                              rgba(0, 0, 0, 0.4),
                                                              rgba(0, 0, 0, 0.2)),
                                                              url('https://images.unsplash.com/photo-1592212532206-a39d1bad53ea?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032')
                                                          ;
                                                          ">
  <h1 class="home-h1">Discover plants in your city!</h1>
  <div class="home-search mt-3 input-group">

    <%= form_tag plants_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control rounded",
      placeholder: "Type your city..."
    %>
    <%= submit_tag "Search...", class: "btn btn-outline" %>
    <% end %>
  </div>
</div>
  <div class="box-area">
    <div class="single-box">
      <div class="img-area"></div>
      <div class="img-text">
        <span class="header-text"><strong>Learn how to raise a plant baby</strong></span>
        <p>Have you never taken care of plants before? Always find that you buy new babies, only for them to die a few months later? No problem. Rent-A-Plant allows you to babysit other plants and practice being a parent before you get your own.</p>
      </div>
    </div>
    <div class="single-box">
      <div class="img-area"></div>
      <div class="img-text">
        <span class="header-text"><strong>Connect with plant lovers nearby</strong></span>
        <p> The great thing about renting plants is that it also allows you to meet like-minded plant baby lovers in your area. Making friends and meeting new people is a great benefit of renting plants! Who knows, maybe you'll find your future spouse! </p>
      </div>
    </div>
    <div class="single-box">
      <div class="img-area"></div>
      <div class="img-text">
        <span class="header-text"><strong>Discover different plant species</strong></span>
        <p>Thinking of getting a new plant species that you've never taken care of? Why not rent it first!? Renting plants allows you to see how a plant species behaves and responds to light and water. The owner will always give you valuable knowledge.</p>
      </div>
    </div>
  </div>

app/views/plants/_form.html.erb
<div class="container-fluid">
  <div class="backgroundimg" style="background-image: linear-gradient(
                                                            180deg,
                                                              rgba(0, 0, 0, 0.4),
                                                              rgba(0, 0, 0, 0.2)),
                                                              url('https://images.unsplash.com/photo-1604762511431-6280a12cb835?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=60&raw_url=true&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aG91c2UlMjBwbGFudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500')
                                                          ;
                                                          ">
    <div class="container text-center pt-5">
      <h1 class="new-form-header pt-3 font-weight-bold">Add a new plant for rent!</h1>
      <p>Please give us details about your plant baby!</p>
    </div>

    <div class="container d-flex mt-5">
      <div class="m-auto">
        <div class="inputs-stuff m-auto">
          <%= simple_form_for plant do |r| %>
            <div class="row form-container">
              <div class="col">
                <%= r.input :name %>
              </div>
              <div class="col">
                <%= r.input :plant_type %>
              </div>
              <%= r.input :description %>
              <%= r.input :city %>
              <div class="col">
                <%= r.input :age, class: 'mt-4' %>
              </div>
              <div class="col">
                <%= r.input :price %>
              </div>
            <%= r.input :photo, as: :file %>
            <%= r.button :submit, class: 'new-button'%>
          <% end %>
        </div>
      </div>
    </div>
    <%# <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_IwKi9V.json" background="transparent" class="lottie-plants-index" speed="1"  style="width: 25em; height:22em;" loop autoplay></lottie-player> %>
  </div>
</div>

app/views/plants/_index_flex_block.erb
<% @plants.each do |plant| %>
    <%= link_to plant_path(plant), class: "plants-index__container w-inline-block" do %>
      <div class="plants-index__img-wrp">
        <%= cl_image_tag(plant.photo.key, class: "plants-index__img") %>
      </div>
      <div class="plants-index__details-wrp">
        <h2 class="plants-index__name"><strong class="bold-text"><%= plant.name %></strong></h2>
        <div class="plants-index__price-div">
          <h3 class="plants-index__price is--currency">€</h3>
          <h3 class="plants-index__price"><%= plant.price %></h3>
        </div>
      </div>
    <% end %>
<%end%>

app/views/plants/index.html.erb
<section class="section">
    <div class="l-container is--plants-index">
      <% if params[:query].present? && @plants.size > 0 %>
        <h1 class="plants-index__h1">Plants Catalogue in <%= params[:query].capitalize %></h1>
        <div class="plants-index">
          <%= render "index_flex_block" %>
        </div>

      <% elsif params[:query].present? && @plants.size == 0 %>
        <div class="plants-index__error-box">
          <div class="plants-index__txt-wrp">
            <h2 class="plants-index__h2">Sorry, there are no plants in <%= params[:query].capitalize %> </h2>
            <h3 class="plants-index__h3">Check below out all our available plants around the globe</h3>
          </div>
          <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_IwKi9V.json" background="transparent" class="lottie-plants-index" speed="1"  style="width: 25em; height:22em;" loop autoplay></lottie-player>
        </div>
        <hr style="margin-bottom: 9em;">
        <h1 class="plants-index__h1">Plants Catalogue</h1>

        <div class="plants-index">
          <% Plant.all.each do |plant| %>
            <%= link_to plant_path(plant), class: "plants-index__container w-inline-block" do %>
              <div class="plants-index__img-wrp">
                <%= cl_image_tag(plant.photo.key, class: "plants-index__img") %>
              </div>
              <div class="plants-index__details-wrp">
                <h2 class="plants-index__name"><strong class="bold-text"><%= plant.name %></strong></h2>
                <div class="plants-index__price-div">
                  <h3 class="plants-index__price is--currency">€</h3>
                  <h3 class="plants-index__price"><%= plant.price %></h3>
                </div>
              </div>
            <% end %>
          <%end%>

        </div>
      <% else %>
        <h1 class="plants-index__h1">Plants Catalogue</h1>
        <div class="plants-index">
          <%= render "index_flex_block" %>
        </div>
      <%end%>
  </section>

app/views/plants/new.html.erb
<%= render 'form', plant: @plant %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer justify-content-center">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github icon-2x"></i></a>
    <a href="#"><i class="fab fa-instagram icon-2x"></i></a>
    <a href="#"><i class="fab fa-facebook icon-2x"></i></a>
    <a href="#"><i class="fab fa-twitter icon-2x"></i></a>
    <a href="#"><i class="fab fa-linkedin icon-2x"></i></a>
  </div>
  <div class="footer-copyright">
    <p>&copy;2022 Rent-A-Plant, Inc. All rights reserved. Designed with love by <span>WePick.</span></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon"
  data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar">

  <div class="container-fluid">

    <a class="navbar-brand" href="/">
      <%= image_tag 'full-logo-transparent.png'
       %></a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <%# <li class="nav-item navigation-links"> %>
        <%#= link_to "Home", root_path %>
        <%# </li> %>
        <li class="nav-item navigation-links">
        <%= link_to "Plants Catalogue", plants_path %>
        </li>

        <%if user_signed_in? %>
          <li class="nav-item dropdown">
          <a class="dropdown-toggle" href="" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag("/img-avatar-beata.jpeg", class: "img-profile-rounded") %>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-box" style="top: 48px;" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "nav-item dropdown linki" %>
            <%= link_to "Add your own plant", new_plant_path, class: "nav-item dropdown linki"%>
            <%= link_to "Logout", destroy_user_session_path, class: "nav-item dropdown linki" %>
          </div>
        <%else%>
          <%= link_to "Login", new_user_session_path, class: 'nav-item button login' %>
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-item button signup' %>
        <%end%>

          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>